os:
  - linux

language: python

stages:
  - Test
  - Sonar
  - Coverage

addons:
  sonarcloud:
    organization: "myprojects"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: Test
      python: 3.6

      install:
        - pip install -r requirements.txt

      script:
        - nosetests -v
    
    - stage: Test
      python: 3.5

      install:
        - pip install -r requirements.txt

      script:
        - pytest -v
    
    - stage: Sonar
      python: 3.6
      install:
        - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
      
      before_script:
        - unzip sonar-scanner-cli-3.2.0.1227-linux.zip -d /opt
        - export PATH=/opt/sonar-scanner-cli-3.2.0.1227-linux/bin:$PATH
      
      script:
        - pytest -v
      
      after_success:
        - sonar-scanner
      
    - stage: Coverage
      script:
        - coverage run --source jxctl setup.py test
        - codecov
    
notifications:
  slack: deepan10:g0F1yGouO4Sj4034QN125LD0