os:
  - linux
  
language: python

cache:
    directories:
     - .tox/
     - /opt/

addons:
  sonarcloud:
    organization: "myprojects"
    token:
      secure: $SONAR_TOKEN

install:
  - sudo pip install tox
  - sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip

before_script:
  - sudo unzip sonar-scanner-cli-3.2.0.1227-linux.zip -d /opt
  - export PATH=/opt/sonar-scanner-cli-3.2.0.1227-linux/bin:$PATH

script:
  - tox

after_success:
  - sonar-scanner

notifications:
  slack: deepan10:g0F1yGouO4Sj4034QN125LD0